package ASSIGNMENT_3;

import java.util.Random;
import java.util.Scanner;
public class HW_3 {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        Random Random_number = new Random();
        int r_num = Random_number.nextInt(12);
        int month = r_num + 1;

        System.out.print("Random number generated by computer is " + month + " and the month is ");

        switch (month) {
            case 1 : System.out.print("January");
            break;
            case 2 : System.out.print("February");
            break;
            case 3 : System.out.print("March");
            break;
            case 4 : System.out.print("April");
            break;
            case 5 : System.out.print("May");
            break;
            case 6 : System.out.print("June");
            break;
            case 7 : System.out.print("July");
            break;
            case 8 : System.out.print("August");
            break;
            case 9 : System.out.print("September");
            break;
            case 10 : System.out.print("October");
            break;
            case 11 : System.out.print("November");
            break;
            case 12 : System.out.print("December");
            break;
        }
        sc.close();
    }
}